#!/bin/bash

url=$1
host=`echo $url | sed -E 's|https*://([^/^:]+).*+$|\1|g'`
srcIP=$2
dstIP=$3
proto=$4
sPort=$5
dPort=$6
LOGFILE=/var/log/webfilter-ng

resp=`echo "$url ${srcIP}/ - - GET" | squidGuard -P`
if [ "$resp" != "ERR" ]
then
    echo DROP
    echo `date +%Y-%m-%d\ %H:%M:%S` $url $proto $srcIP:$sPort $dstIP:$dPort DROP >>$LOGFILE
else
    echo ACCEPT
    echo `date +%Y-%m-%d\ %H:%M:%S` $url $proto $srcIP:$sPort $dstIP:$dPort ACCEPT >>$LOGFILE
fi
exit 0
